/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSiteTextsRouteImport } from './routes/_auth/site-texts'
import { Route as AuthArtistProfileRouteImport } from './routes/_auth/artist-profile'
import { Route as AuthWorksIndexRouteImport } from './routes/_auth/works/index'
import { Route as AuthCommissionIndexRouteImport } from './routes/_auth/commission/index'
import { Route as AuthWorksNewRouteImport } from './routes/_auth/works/new'
import { Route as AuthEpisodesNewRouteImport } from './routes/_auth/episodes/new'
import { Route as AuthCommissionNewRouteImport } from './routes/_auth/commission/new'
import { Route as AuthCommissionItemIdRouteImport } from './routes/_auth/commission/$itemId'
import { Route as AuthWorksWorkIdIndexRouteImport } from './routes/_auth/works/$workId/index'
import { Route as AuthWorksWorkIdEpisodesIndexRouteImport } from './routes/_auth/works/$workId/episodes/index'
import { Route as AuthWorksWorkIdEpisodesUploadRouteImport } from './routes/_auth/works/$workId/episodes/upload'
import { Route as AuthWorksWorkIdEpisodesEpisodeIdRouteImport } from './routes/_auth/works/$workId/episodes/$episodeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSiteTextsRoute = AuthSiteTextsRouteImport.update({
  id: '/site-texts',
  path: '/site-texts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArtistProfileRoute = AuthArtistProfileRouteImport.update({
  id: '/artist-profile',
  path: '/artist-profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorksIndexRoute = AuthWorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCommissionIndexRoute = AuthCommissionIndexRouteImport.update({
  id: '/commission/',
  path: '/commission/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorksNewRoute = AuthWorksNewRouteImport.update({
  id: '/works/new',
  path: '/works/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEpisodesNewRoute = AuthEpisodesNewRouteImport.update({
  id: '/episodes/new',
  path: '/episodes/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCommissionNewRoute = AuthCommissionNewRouteImport.update({
  id: '/commission/new',
  path: '/commission/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCommissionItemIdRoute = AuthCommissionItemIdRouteImport.update({
  id: '/commission/$itemId',
  path: '/commission/$itemId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorksWorkIdIndexRoute = AuthWorksWorkIdIndexRouteImport.update({
  id: '/works/$workId/',
  path: '/works/$workId/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorksWorkIdEpisodesIndexRoute =
  AuthWorksWorkIdEpisodesIndexRouteImport.update({
    id: '/works/$workId/episodes/',
    path: '/works/$workId/episodes/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorksWorkIdEpisodesUploadRoute =
  AuthWorksWorkIdEpisodesUploadRouteImport.update({
    id: '/works/$workId/episodes/upload',
    path: '/works/$workId/episodes/upload',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorksWorkIdEpisodesEpisodeIdRoute =
  AuthWorksWorkIdEpisodesEpisodeIdRouteImport.update({
    id: '/works/$workId/episodes/$episodeId',
    path: '/works/$workId/episodes/$episodeId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/artist-profile': typeof AuthArtistProfileRoute
  '/site-texts': typeof AuthSiteTextsRoute
  '/commission/$itemId': typeof AuthCommissionItemIdRoute
  '/commission/new': typeof AuthCommissionNewRoute
  '/episodes/new': typeof AuthEpisodesNewRoute
  '/works/new': typeof AuthWorksNewRoute
  '/commission/': typeof AuthCommissionIndexRoute
  '/works/': typeof AuthWorksIndexRoute
  '/works/$workId/': typeof AuthWorksWorkIdIndexRoute
  '/works/$workId/episodes/$episodeId': typeof AuthWorksWorkIdEpisodesEpisodeIdRoute
  '/works/$workId/episodes/upload': typeof AuthWorksWorkIdEpisodesUploadRoute
  '/works/$workId/episodes/': typeof AuthWorksWorkIdEpisodesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/artist-profile': typeof AuthArtistProfileRoute
  '/site-texts': typeof AuthSiteTextsRoute
  '/': typeof AuthIndexRoute
  '/commission/$itemId': typeof AuthCommissionItemIdRoute
  '/commission/new': typeof AuthCommissionNewRoute
  '/episodes/new': typeof AuthEpisodesNewRoute
  '/works/new': typeof AuthWorksNewRoute
  '/commission': typeof AuthCommissionIndexRoute
  '/works': typeof AuthWorksIndexRoute
  '/works/$workId': typeof AuthWorksWorkIdIndexRoute
  '/works/$workId/episodes/$episodeId': typeof AuthWorksWorkIdEpisodesEpisodeIdRoute
  '/works/$workId/episodes/upload': typeof AuthWorksWorkIdEpisodesUploadRoute
  '/works/$workId/episodes': typeof AuthWorksWorkIdEpisodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/artist-profile': typeof AuthArtistProfileRoute
  '/_auth/site-texts': typeof AuthSiteTextsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/commission/$itemId': typeof AuthCommissionItemIdRoute
  '/_auth/commission/new': typeof AuthCommissionNewRoute
  '/_auth/episodes/new': typeof AuthEpisodesNewRoute
  '/_auth/works/new': typeof AuthWorksNewRoute
  '/_auth/commission/': typeof AuthCommissionIndexRoute
  '/_auth/works/': typeof AuthWorksIndexRoute
  '/_auth/works/$workId/': typeof AuthWorksWorkIdIndexRoute
  '/_auth/works/$workId/episodes/$episodeId': typeof AuthWorksWorkIdEpisodesEpisodeIdRoute
  '/_auth/works/$workId/episodes/upload': typeof AuthWorksWorkIdEpisodesUploadRoute
  '/_auth/works/$workId/episodes/': typeof AuthWorksWorkIdEpisodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/artist-profile'
    | '/site-texts'
    | '/commission/$itemId'
    | '/commission/new'
    | '/episodes/new'
    | '/works/new'
    | '/commission/'
    | '/works/'
    | '/works/$workId/'
    | '/works/$workId/episodes/$episodeId'
    | '/works/$workId/episodes/upload'
    | '/works/$workId/episodes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/artist-profile'
    | '/site-texts'
    | '/'
    | '/commission/$itemId'
    | '/commission/new'
    | '/episodes/new'
    | '/works/new'
    | '/commission'
    | '/works'
    | '/works/$workId'
    | '/works/$workId/episodes/$episodeId'
    | '/works/$workId/episodes/upload'
    | '/works/$workId/episodes'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/artist-profile'
    | '/_auth/site-texts'
    | '/_auth/'
    | '/_auth/commission/$itemId'
    | '/_auth/commission/new'
    | '/_auth/episodes/new'
    | '/_auth/works/new'
    | '/_auth/commission/'
    | '/_auth/works/'
    | '/_auth/works/$workId/'
    | '/_auth/works/$workId/episodes/$episodeId'
    | '/_auth/works/$workId/episodes/upload'
    | '/_auth/works/$workId/episodes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/site-texts': {
      id: '/_auth/site-texts'
      path: '/site-texts'
      fullPath: '/site-texts'
      preLoaderRoute: typeof AuthSiteTextsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/artist-profile': {
      id: '/_auth/artist-profile'
      path: '/artist-profile'
      fullPath: '/artist-profile'
      preLoaderRoute: typeof AuthArtistProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/works/': {
      id: '/_auth/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof AuthWorksIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/': {
      id: '/_auth/commission/'
      path: '/commission'
      fullPath: '/commission/'
      preLoaderRoute: typeof AuthCommissionIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/works/new': {
      id: '/_auth/works/new'
      path: '/works/new'
      fullPath: '/works/new'
      preLoaderRoute: typeof AuthWorksNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/episodes/new': {
      id: '/_auth/episodes/new'
      path: '/episodes/new'
      fullPath: '/episodes/new'
      preLoaderRoute: typeof AuthEpisodesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/new': {
      id: '/_auth/commission/new'
      path: '/commission/new'
      fullPath: '/commission/new'
      preLoaderRoute: typeof AuthCommissionNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/$itemId': {
      id: '/_auth/commission/$itemId'
      path: '/commission/$itemId'
      fullPath: '/commission/$itemId'
      preLoaderRoute: typeof AuthCommissionItemIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/works/$workId/': {
      id: '/_auth/works/$workId/'
      path: '/works/$workId'
      fullPath: '/works/$workId/'
      preLoaderRoute: typeof AuthWorksWorkIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/works/$workId/episodes/': {
      id: '/_auth/works/$workId/episodes/'
      path: '/works/$workId/episodes'
      fullPath: '/works/$workId/episodes/'
      preLoaderRoute: typeof AuthWorksWorkIdEpisodesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/works/$workId/episodes/upload': {
      id: '/_auth/works/$workId/episodes/upload'
      path: '/works/$workId/episodes/upload'
      fullPath: '/works/$workId/episodes/upload'
      preLoaderRoute: typeof AuthWorksWorkIdEpisodesUploadRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/works/$workId/episodes/$episodeId': {
      id: '/_auth/works/$workId/episodes/$episodeId'
      path: '/works/$workId/episodes/$episodeId'
      fullPath: '/works/$workId/episodes/$episodeId'
      preLoaderRoute: typeof AuthWorksWorkIdEpisodesEpisodeIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthArtistProfileRoute: typeof AuthArtistProfileRoute
  AuthSiteTextsRoute: typeof AuthSiteTextsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCommissionItemIdRoute: typeof AuthCommissionItemIdRoute
  AuthCommissionNewRoute: typeof AuthCommissionNewRoute
  AuthEpisodesNewRoute: typeof AuthEpisodesNewRoute
  AuthWorksNewRoute: typeof AuthWorksNewRoute
  AuthCommissionIndexRoute: typeof AuthCommissionIndexRoute
  AuthWorksIndexRoute: typeof AuthWorksIndexRoute
  AuthWorksWorkIdIndexRoute: typeof AuthWorksWorkIdIndexRoute
  AuthWorksWorkIdEpisodesEpisodeIdRoute: typeof AuthWorksWorkIdEpisodesEpisodeIdRoute
  AuthWorksWorkIdEpisodesUploadRoute: typeof AuthWorksWorkIdEpisodesUploadRoute
  AuthWorksWorkIdEpisodesIndexRoute: typeof AuthWorksWorkIdEpisodesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthArtistProfileRoute: AuthArtistProfileRoute,
  AuthSiteTextsRoute: AuthSiteTextsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCommissionItemIdRoute: AuthCommissionItemIdRoute,
  AuthCommissionNewRoute: AuthCommissionNewRoute,
  AuthEpisodesNewRoute: AuthEpisodesNewRoute,
  AuthWorksNewRoute: AuthWorksNewRoute,
  AuthCommissionIndexRoute: AuthCommissionIndexRoute,
  AuthWorksIndexRoute: AuthWorksIndexRoute,
  AuthWorksWorkIdIndexRoute: AuthWorksWorkIdIndexRoute,
  AuthWorksWorkIdEpisodesEpisodeIdRoute: AuthWorksWorkIdEpisodesEpisodeIdRoute,
  AuthWorksWorkIdEpisodesUploadRoute: AuthWorksWorkIdEpisodesUploadRoute,
  AuthWorksWorkIdEpisodesIndexRoute: AuthWorksWorkIdEpisodesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
