"""work episode domain models

Revision ID: 7b5367aada9a
Revises: 5a55bab9de3d
Create Date: 2026-07-01 11:25:59.157661+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b5367aada9a'
down_revision: Union[str, Sequence[str], None] = '5a55bab9de3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('works',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('episode_base_price', sa.Integer(), server_default=sa.text('500'), nullable=False),
    sa.Column('bundle_discount_rate', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.1'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ongoing'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('work_id', sa.UUID(), nullable=False),
    sa.Column('episode_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('image_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'episode_no', name='uq_episodes_work_id_episode_no')
    )
    op.create_index('idx_episodes_published', 'episodes', ['work_id'], unique=False, postgresql_where=sa.text('is_published = true'))
    op.create_index('idx_episodes_published_at', 'episodes', ['published_at'], unique=False, postgresql_where=sa.text('is_published = true'))
    op.create_index('idx_episodes_work_id', 'episodes', ['work_id'], unique=False)
    op.create_table('works_tags',
    sa.Column('work_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works_tags')
    op.drop_index('idx_episodes_work_id', table_name='episodes')
    op.drop_index('idx_episodes_published_at', table_name='episodes', postgresql_where=sa.text('is_published = true'))
    op.drop_index('idx_episodes_published', table_name='episodes', postgresql_where=sa.text('is_published = true'))
    op.drop_table('episodes')
    op.drop_table('works')
    op.drop_table('tags')
    # ### end Alembic commands ###
