"""user role rbac and totp columns

Revision ID: 9a25c6be3759
Revises: 7b5367aada9a
Create Date: 2026-07-01 17:09:08.317614+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a25c6be3759'
down_revision: Union[str, Sequence[str], None] = '7b5367aada9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=16), server_default=sa.text("'reader'"), nullable=False))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('totp_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # is_admin(boolean) -> role(RBAC) 데이터 이관: 기존 관리자(is_admin=true)를 owner로.
    # drop_column 전에 실행해야 값이 보존된다(autogenerate는 이 UPDATE를 만들지 못한다).
    op.execute("UPDATE users SET role = 'owner' WHERE is_admin = true")
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # 역이관: owner였던 유저만 is_admin=true로 복원(moderator는 M1.5에 없어 무손실).
    op.execute("UPDATE users SET is_admin = true WHERE role = 'owner'")
    op.drop_column('users', 'totp_confirmed_at')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
