"""works is_published flag

Revision ID: 726b16a759b3
Revises: 2a9ae60edceb
Create Date: 2026-07-17 08:43:14.860592+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '726b16a759b3'
down_revision: Union[str, Sequence[str], None] = '2a9ae60edceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
    # 기존 작품은 이미 운영 중이던 데이터라 공개 유지(신규 작품만 기본 비공개) - M2 그룹 A 결정.
    op.execute("UPDATE works SET is_published = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'is_published')
    # ### end Alembic commands ###
