"""add trusted_devices

Revision ID: 4d1613a602e5
Revises: 9a25c6be3759
Create Date: 2026-07-07 17:07:49.243860+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d1613a602e5'
down_revision: Union[str, Sequence[str], None] = '9a25c6be3759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trusted_devices_user_id', 'trusted_devices', ['user_id'], unique=False)
    op.create_index('uq_trusted_devices_token_hash', 'trusted_devices', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trusted_devices_token_hash', table_name='trusted_devices')
    op.drop_index('idx_trusted_devices_user_id', table_name='trusted_devices')
    op.drop_table('trusted_devices')
    # ### end Alembic commands ###
