"""totp last step

Revision ID: e8ce7c708538
Revises: 482e29d1df31
Create Date: 2026-07-21 16:17:56.518493+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8ce7c708538'
down_revision: Union[str, Sequence[str], None] = '482e29d1df31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_last_step', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_last_step')
    # ### end Alembic commands ###
