/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Login
         * @description 구글 동의 화면으로 302. state(CSRF)·nonce(replay)를 생성해 oauth_tx 쿠키로 운반한다.
         */
        get: operations["google_login_auth_login_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Callback
         * @description 구글 콜백. code 교환 -> id_token 검증 -> 유저 확정 -> 인증 쿠키 set 후 홈으로 302.
         *
         *     실패(동의 거부/파라미터 누락/state 위조/검증 실패/이미 가입)는 프론트 로그인 페이지로
         *     generic 코드와 함께 302. oauth_tx 쿠키는 처리 후 일회용으로 소비한다.
         */
        get: operations["google_callback_auth_callback_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/2fa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Totp Setup */
        post: operations["totp_setup_admin_2fa_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/2fa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Totp Confirm */
        post: operations["totp_confirm_admin_2fa_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Login
         * @description 관리자 로그인 1단계. 미등록 owner는 등록 게이트, 신뢰 기기는 즉시 완료, 그 외 TOTP 대기.
         *
         *     실패는 /auth/login과 동일한 generic 401(비열거 - 관리자 계정 여부 비노출).
         */
        post: operations["admin_login_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Login Totp
         * @description 관리자 로그인 2단계: TOTP 코드 검증 → 인증 쿠키 발급(+옵트인 신뢰 기기).
         */
        post: operations["admin_login_totp_admin_login_totp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Works */
        get: operations["list_works_admin_works_get"];
        put?: never;
        /** Create Work */
        post: operations["create_work_admin_works_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/works/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work */
        get: operations["get_work_admin_works__work_id__get"];
        /** Update Work */
        put: operations["update_work_admin_works__work_id__put"];
        post?: never;
        /** Delete Work */
        delete: operations["delete_work_admin_works__work_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/works/{work_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Cover
         * @description 표지 단건 업로드(M1.5 D3, C1 이연분): 변환 → works/{id}/cover.webp 덮어쓰기.
         *
         *     표지는 에피소드 페이지와 별개 파일이다(회차 썸네일 선택은 에피소드 PUT의
         *     thumbnail - 그쪽은 업로드된 페이지 중 선택, 여기는 독립 일러스트 업로드).
         */
        post: operations["upload_cover_admin_works__work_id__cover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/works/{work_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Episodes
         * @description episode_no 순 목록(삭제분 제외). image_keys 포함(F3 재배열 UI 소비)이라 상세 GET은 없다.
         */
        get: operations["list_episodes_admin_works__work_id__episodes_get"];
        put?: never;
        /**
         * Create Episode
         * @description draft 생성(JSON, 이미지 없음). episode_no 중복은 이미지 업로드 전에 즉시 409.
         */
        post: operations["create_episode_admin_works__work_id__episodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/works/{work_id}/episodes/{episode_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Episode Image
         * @description 페이지 1장 업로드: 변환(D2) → R2(D1) → image_keys 끝에 원자 append.
         *
         *     F3가 페이지 순서대로 반복 호출한다(진행바 = 장 단위). 실패한 장만 재시도하면
         *     되고, 최종 순서는 PUT 재배열로 조정 가능하다.
         */
        post: operations["upload_episode_image_admin_works__work_id__episodes__episode_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/works/{work_id}/episodes/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Episode
         * @description 메타 부분수정(JSON) + 페이지 재배열/삭제 + 썸네일 선택 + 공개(즉시/예약).
         */
        put: operations["update_episode_admin_works__work_id__episodes__episode_id__put"];
        post?: never;
        /**
         * Delete Episode
         * @description 회차 soft delete (#85). 공개 중인 회차도 지울 수 있고, 삭제와 동시에 공개가 풀린다.
         *
         *     이미 삭제된 회차는 404다(_episode_or_404가 deleted_at을 본다) - DELETE를 멱등하게
         *     두지 않은 건 "지웠는데 204가 또 온다"보다 "그 회차는 이미 없다"가 관리자에게
         *     정확한 정보이기 때문. 되살리는 엔드포인트는 두지 않는다.
         */
        delete: operations["delete_episode_admin_works__work_id__episodes__episode_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/works/{work_id}/episodes/{episode_id}/image-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Episode Image Urls
         * @description 업로드된 페이지의 presigned GET URL(image_keys 순서). 관리자 미리보기 전용.
         *
         *     원래 M3(결제·잠금) 소관이던 GET 발급을 F3 업로드 화면(draft 재진입 미리보기·
         *     재배열·썸네일 선택)용으로 앞당김(2026-07-15). 매 요청 새로 발급하고 캐시하지
         *     않는다(backend/CLAUDE.md Signed URL 규칙).
         */
        get: operations["get_episode_image_urls_admin_works__work_id__episodes__episode_id__image_urls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Works */
        get: operations["list_works_works_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work */
        get: operations["get_work_works__work_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works/{work_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Work Episodes
         * @description 공개 회차 목록 (M2 B1). GET /works/{id}(A2)의 episodes와 같은 배열을, 작품 메타
         *     없이 필요한 소비자(뷰어 네비 등)를 위해 단독으로 낸다.
         */
        get: operations["list_work_episodes_works__work_id__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{episode_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Episode Content
         * @description 무료 구간 본문(유료 경계 이전)을 presigned URL로 치환해 반환한다.
         */
        get: operations["get_episode_content_episodes__episode_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{episode_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Progress */
        get: operations["read_progress_episodes__episode_id__progress_get"];
        /** Update Progress */
        put: operations["update_progress_episodes__episode_id__progress_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminEpisodeRead
         * @description 관리자(owner) 응답 **전용** - 이름부터 Admin: image_keys(R2 키)를 노출하므로
         *     독자용 라우터(M2)가 무심코 재사용하면 미결제 유저에게 키가 새는 경로가 된다.
         *     독자 뷰어 응답은 M2에서 image_keys를 제외한 별도 DTO(Signed URL만)로 만든다.
         */
        AdminEpisodeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Work Id
             * Format: uuid
             */
            work_id: string;
            /** Episode No */
            episode_no: number;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string | null;
            /** Thumbnail */
            thumbnail: string | null;
            /** Price */
            price: number | null;
            /** Is Free */
            is_free: boolean;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            draft: components["schemas"]["EpisodeDraft"] | null;
            /** Image Keys */
            image_keys: string[];
            /** Is Published */
            is_published: boolean;
            /** Published At */
            published_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Thumbnail Url */
            readonly thumbnail_url: string | null;
        };
        /** AdminLoginResponse */
        AdminLoginResponse: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "totp" | "totp_setup" | "complete";
        };
        /** Body_upload_cover_admin_works__work_id__cover_post */
        Body_upload_cover_admin_works__work_id__cover_post: {
            /** Image */
            image: string;
        };
        /** Body_upload_episode_image_admin_works__work_id__episodes__episode_id__images_post */
        Body_upload_episode_image_admin_works__work_id__episodes__episode_id__images_post: {
            /** Image */
            image: string;
        };
        /**
         * EpisodeContent
         * @description 무료 구간 본문 응답 (M2 B2). 회차 메타·네비는 GET /works/{id}(A2)가 담당한다.
         */
        EpisodeContent: {
            /**
             * Episode Id
             * Format: uuid
             */
            episode_id: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /** Has Paid Part */
            has_paid_part: boolean;
        };
        /**
         * EpisodeCreate
         * @description draft 생성(is_published=false). 이미지·본문은 이후 요청(D3 구조 A + F3 에디터 PUT).
         *
         *     F3 재설계(2026-07-15): 에디터가 "캔버스 먼저, 메타는 발행 모달" 흐름이라
         *     episode_no 생략 = 서버가 해당 작품 max+1 자동 할당, title 생략 = "무제".
         *     is_free는 입력에서 제거 - content의 유료 경계에서 서버가 파생하는 컬럼이 됐다.
         *
         *     thumbnail이 없는 이유는 기존과 동일 - 생성 시점엔 검증할 image_keys가 없어
         *     임의 키 주입 통로가 된다. published_at은 예약 공개 시각 - **과거 시각도 허용**
         *     (스케줄러 다음 틱 공개). AwareDatetime이라 naive 시각은 422(KST가 UTC로
         *     오해석돼 9시간 밀리는 조용한 오동작 차단).
         */
        EpisodeCreate: {
            /** Episode No */
            episode_no?: number | null;
            /**
             * Title
             * @default 무제
             */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Price */
            price?: number | null;
            /** Published At */
            published_at?: string | null;
        };
        /**
         * EpisodeDraft
         * @description 편집본 봉투(#86) - episodes.draft JSONB에 통째로 저장된다.
         *
         *     본문만 담으면 공개 회차의 제목·부제 수정이 여전히 임시저장 즉시 라이브 반영되는
         *     반쪽 분리가 되므로 메타까지 스냅샷한다. content 검증(화이트리스트·상한·키 소유)은
         *     image_keys가 필요해 service(lib/content_doc)가 수행한다.
         */
        EpisodeDraft: {
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Content */
            content: {
                [key: string]: unknown;
            };
        };
        /**
         * EpisodeImageUrl
         * @description 페이지 1장의 R2 키 + presigned GET URL 쌍. 관리자 미리보기 응답 전용.
         *
         *     URL만 주지 않고 키를 함께 주는 이유: 재배열·썸네일 선택 UI가 "이 이미지 = 어느
         *     키"의 매핑을 알아야 PUT(image_keys 부분집합·thumbnail 키)을 만들 수 있다.
         *     url은 PRESIGN_GET_EXPIRES 후 만료되는 일회성 값 - 저장·캐시 금지.
         */
        EpisodeImageUrl: {
            /** Key */
            key: string;
            /** Url */
            url: string;
        };
        /** EpisodeSummary */
        EpisodeSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Episode No */
            episode_no: number;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Is Free */
            is_free: boolean;
            /** Is Locked */
            is_locked: boolean;
            /** Is Purchased */
            is_purchased: boolean;
            /** Price */
            price: number | null;
        };
        /**
         * EpisodeUpdate
         * @description 부분 수정. 생략 = 미변경, 명시적 null은 nullable 컬럼(subtitle·price·thumbnail·
         *     published_at·draft)만.
         *
         *     - content: 본문(TipTap JSON - lib/content_doc 화이트리스트·상한·이미지 키 소유 검증).
         *       유료 경계(paywall 노드) 위치가 곧 무료/유료 분량이고 is_free는 서버가 파생한다
         *       (직접 입력 폐지 - F3 재설계 2026-07-15).
         *     - image_keys: 업로드 매니페스트 정리(삭제). 기존 키의 중복 없는 부분집합만(service
         *       검증 - 임의 키 주입 금지). 표시 순서의 진실은 content로 이동했다.
         *     - thumbnail: 회차 대표 컷. 이 회차 image_keys 중 하나여야 하며(작가가 표지 일러스트
         *       페이지를 직접 선택 - 첫 페이지가 표지가 아닌 웹툰 관행), null = 해제.
         *     - is_published=true: 즉시 공개 - published_at이 없으면(NULL·미래) 서버가 now로 스탬프,
         *       본문에 유의미 내용(글/이미지) 필요. false 전환 시 published_at은 **페이로드와
         *       무관하게 항상 NULL 초기화**(E1 부활 차단 - stale 에코 방어. 재예약은 is_published
         *       없이 published_at만 별도 요청). published_at 과거값 = 다음 틱 공개(E1).
         *       naive 시각은 422(AwareDatetime).
         *     - draft: 편집본 봉투(#86). content(발행본)와 **동시 전송 불가**(422) - "임시저장"과
         *       "발행"은 다른 액션이다. 명시적 null = 편집본 버리기. content가 오는 요청은 서버가
         *       draft를 NULL로 비운다(발행 = 편집본 소진).
         */
        EpisodeUpdate: {
            /** Episode No */
            episode_no?: number | null;
            /** Title */
            title?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Price */
            price?: number | null;
            /** Is Published */
            is_published?: boolean | null;
            /** Thumbnail */
            thumbnail?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Image Keys */
            image_keys?: string[] | null;
            /** Content */
            content?: {
                [key: string]: unknown;
            } | null;
            draft?: components["schemas"]["EpisodeDraft"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** ProgressRead */
        ProgressRead: {
            /**
             * Episode Id
             * Format: uuid
             */
            episode_id: string;
            /** Page No */
            page_no: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProgressUpdate */
        ProgressUpdate: {
            /** Page No */
            page_no: number;
        };
        /** PublicTag */
        PublicTag: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Work Count */
            work_count: number;
        };
        /** ResendVerificationRequest */
        ResendVerificationRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * RoleEnum
         * @description 유저 권한 (DECISIONS "관리자 권한 분리" = 3-역할 RBAC).
         *
         *     VARCHAR(16)에 멤버 값을 그대로 저장(네이티브 PG enum 아님) - 후속 역할 추가는
         *     앱 enum 값만 늘리면 되고 DB 마이그레이션이 필요 없다(MISTAKES StrEnum 패턴).
         *     authz 진실 소스는 JWT claim이 아니라 DB user.role(get_current_user가 매 요청 User 로드).
         *     M1.5는 owner만 프로비저닝(moderator=M4, reader=전 유저 기본값).
         * @enum {string}
         */
        RoleEnum: "reader" | "owner" | "moderator";
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Nickname */
            nickname: string;
        };
        /** TagRead */
        TagRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** TotpConfirmRequest */
        TotpConfirmRequest: {
            /** Code */
            code: string;
            /**
             * Remember Device
             * @default false
             */
            remember_device: boolean;
        };
        /** TotpSetupResponse */
        TotpSetupResponse: {
            /** Otpauth Uri */
            otpauth_uri: string;
        };
        /**
         * UserRead
         * @description 외부 응답 전용 스키마. 민감 필드(hashed_password 등) 제외 (M1 C5 /auth/me).
         */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Nickname */
            nickname: string;
            /** Profile Image */
            profile_image: string | null;
            /** Is Email Verified */
            is_email_verified: boolean;
            role: components["schemas"]["RoleEnum"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
        /** WorkCreate */
        WorkCreate: {
            /** Title */
            title: string;
            /** Synopsis */
            synopsis?: string | null;
            /** Cover Image */
            cover_image?: string | null;
            /**
             * Episode Base Price
             * @default 500
             */
            episode_base_price: number;
            /**
             * Bundle Discount Rate
             * @default 0.1
             */
            bundle_discount_rate: number | string;
            /** @default ongoing */
            status: components["schemas"]["WorkStatus"];
            /**
             * Is Published
             * @default false
             */
            is_published: boolean;
            /** Tag Names */
            tag_names?: string[];
        };
        /** WorkDetail */
        WorkDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Synopsis */
            synopsis: string | null;
            /** Cover Image Url */
            cover_image_url: string | null;
            /** Episode Base Price */
            episode_base_price: number;
            status: components["schemas"]["WorkStatus"];
            /** Tags */
            tags: components["schemas"]["TagRead"][];
            /** Episodes */
            episodes: components["schemas"]["EpisodeSummary"][];
        };
        /** WorkListItem */
        WorkListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Cover Image Url */
            cover_image_url: string | null;
            status: components["schemas"]["WorkStatus"];
            /** Tags */
            tags: components["schemas"]["TagRead"][];
            /** Episode Count */
            episode_count: number;
        };
        /** WorkListResponse */
        WorkListResponse: {
            /** Items */
            items: components["schemas"]["WorkListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** WorkRead */
        WorkRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Author Id
             * Format: uuid
             */
            author_id: string;
            /** Title */
            title: string;
            /** Synopsis */
            synopsis: string | null;
            /** Cover Image */
            cover_image: string | null;
            /** Episode Base Price */
            episode_base_price: number;
            /** Bundle Discount Rate */
            bundle_discount_rate: string;
            status: components["schemas"]["WorkStatus"];
            /** Is Published */
            is_published: boolean;
            /** Tags */
            tags: components["schemas"]["TagRead"][];
            /** Episode Count */
            episode_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Cover Url */
            readonly cover_url: string | null;
        };
        /**
         * WorkStatus
         * @description 작품 연재 상태. VARCHAR(20) 저장(네이티브 PG enum 아님) + 앱 레벨 검증.
         *
         *     StrEnum(str 서브클래스)이라 컬럼(String)에 멤버 값("ongoing" 등)이 그대로 저장된다.
         *     후속 상태 추가는 이 enum 값만 늘리면 되고 DB 마이그레이션이 필요 없다.
         * @enum {string}
         */
        WorkStatus: "ongoing" | "completed" | "hiatus";
        /**
         * WorkUpdate
         * @description 부분 수정. 필드 생략 = 미변경(exclude_unset). None 허용은 컬럼 nullability를 따른다.
         */
        WorkUpdate: {
            /** Title */
            title?: string | null;
            /** Synopsis */
            synopsis?: string | null;
            /** Cover Image */
            cover_image?: string | null;
            /** Episode Base Price */
            episode_base_price?: number | null;
            /** Bundle Discount Rate */
            bundle_discount_rate?: number | string | null;
            status?: components["schemas"]["WorkStatus"] | null;
            /** Is Published */
            is_published?: boolean | null;
            /** Tag Names */
            tag_names?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    verify_email_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_auth_login_google_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_callback_auth_callback_google_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    totp_setup_admin_2fa_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetupResponse"];
                };
            };
        };
    };
    totp_confirm_admin_2fa_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_login_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_login_totp_admin_login_totp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_works_admin_works_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkRead"][];
                };
            };
        };
    };
    create_work_admin_works_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_admin_works__work_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_work_admin_works__work_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_work_admin_works__work_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cover_admin_works__work_id__cover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cover_admin_works__work_id__cover_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_episodes_admin_works__work_id__episodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEpisodeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_episode_admin_works__work_id__episodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEpisodeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_episode_image_admin_works__work_id__episodes__episode_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_episode_image_admin_works__work_id__episodes__episode_id__images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEpisodeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_episode_admin_works__work_id__episodes__episode_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEpisodeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_episode_admin_works__work_id__episodes__episode_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episode_image_urls_admin_works__work_id__episodes__episode_id__image_urls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeImageUrl"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_works_works_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                tag?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_works__work_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_work_episodes_works__work_id__episodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicTag"][];
                };
            };
        };
    };
    get_episode_content_episodes__episode_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_progress_episodes__episode_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_progress_episodes__episode_id__progress_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
